### ISSUE TITLE
Just something worth mentioning

### ISSUE THREAD

**Issue by assarbad** [dishather/richprint#4]
Hi there,

are you aware that a simple `/emittoolversioninfo:no` passed to the linker will prevent some of this information from being embedded?

**Comment by dishather** [comment]
Interesting, thank you!
This option is undocumented, yet it works indeed. I will mention it in the README so that it doesn't get lost.

**Comment by puetzk** [comment]
Just for the sake of link a source, this otherwise-undocumented flag was added per the request https://developercommunity.visualstudio.com/t/add-linker-option-to-strip-rich-stamp-from-exe-hea/740443, and has been available since VS2019 Update 11
