### ISSUE TITLE
Request for Alternative Licensing of comp_id.txt Resources

### ISSUE THREAD

**Issue by PAX523** [dishather/richprint#5]
I've been exploring your project and find the resources it provides to be incredibly valuable for my own software development efforts. However, I have a concern regarding the licensing terms associated with the comp.id resources.

As my software is closed source, I'm unable to comply with the requirements of the GPL license under which the resources are currently distributed. While I fully respect the principles of open source licensing, I require a licensing arrangement that aligns with the proprietary nature of my software.

Would it be possible for you to consider providing the comp.id resources under a license with weaker copyleft provisions or alternative licensing terms that would allow for their use in closed source software? I'm open to discussing any conditions or terms you may have in mind.

Thank you for considering my request. I appreciate your contributions to the open source community and look forward to your response.

Wishing you a blessed Easter!

Best regards,

PAX

**Comment by dishather** [comment]
No problem. Which license would you recommend?

**Comment by PAX523** [comment]
Thank you very much for considering my request to change the license for the project. I appreciate your willingness to accommodate my needs.

After reviewing various licensing options, I believe that the BSD 2-Clause License (Simplified BSD License) would be the most suitable choice for my use case. Here's why:

1. Permissiveness: The BSD 2-Clause License is very permissive, allowing me to include the comp_id.txt resource in my proprietary closed-source software project without imposing significant restrictions.
2. Ease of Use: This license is straightforward and easy to understand, making it convenient for both me as the user and for potential contributors to the project.
3. Compatibility: The BSD 2-Clause License is compatible with a wide range of other licenses, giving me flexibility in how I use and distribute the comp_id.txt resource.

By choosing the BSD 2-Clause License, I can seamlessly integrate the comp_id.txt resource into my project while ensuring compliance with your licensing terms. I understand that you may have other considerations, so please let me know if you have any questions or concerns. Especially when you think, that you rather prefer something more restrictive but with weak copyleft (such as LGPL).

I would also put a link to your GitHub project into the user interface of my software as soon as I integrated it. Do you also would like to see your name there in any form? If yes, please contact me via my contact form for a private conversation (see link in my profile).

Thank you again for your cooperation, and I look forward to your response. And thank you for all your efforts.

Best regards,

PAX

https://www.mend.io/blog/top-open-source-licenses-explained/

https://opensource.org/license/bsd-2-clause

**Comment by dishather** [comment]
Looks good, I've changed the license to BSD 2-clause license.
I think there is no need to mention my name though.

**Comment by dishather** [comment]
Closing.
